name: Fetch Reddit

on:
  schedule:
    - cron: "0 0 * * *" # 毎日0時に実行 (UTC)
  workflow_dispatch: # 手動トリガーも可能

jobs:
  reddit_search:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install praw python-dotenv google-auth google-auth-oauthlib google-auth-httplib2 google-api-python-client

      - name: Run fetch_reddit script
        env:
          REDDIT_CLIENT_ID: ${{ secrets.REDDIT_CLIENT_ID }}
          REDDIT_CLIENT_SECRET: ${{ secrets.REDDIT_CLIENT_SECRET }}
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
          GOOGLE_DRIVE_FOLDER_ID: ${{ secrets.GOOGLE_DRIVE_FOLDER_ID }}
        run: python app/fetch_reddit.py

      - name: Send notification to Discord
        if: success()
        run: |
          curl -H "Content-Type: application/json" \
              -d '{"content": "fetch_reddit.py ran successfully."}' \
              ${{ secrets.DISCORD_WEBHOOK_URL }}

      - name: Send failure notification to Discord
        if: failure()
        run: |
          curl -H "Content-Type: application/json" \
              -d '{"content": "fetch_reddit.py ran failed."}' \
              ${{ secrets.DISCORD_WEBHOOK_URL }}
