name: Fetch Tumblr Posts

on:
  schedule:
    - cron: "0 0 * * *" # 毎日0時に実行
  workflow_dispatch: # 手動トリガーも可能

jobs:
  fetch_tumblr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytumblr python-dotenv

      - name: Run fetch_tumblr script
        env:
          TUMBLR_API_KEY: ${{ secrets.TUMBLR_API_KEY }}
        run: |
          python app/fetch_tumblr.py

      - name: Upload Tumblr data as artifact
        uses: actions/upload-artifact@v2
        with:
          name: tumblr-data
          path: data/tumblr/*.json
