name: Semantic Scholar Search

on:
  schedule:
    - cron: "0 0 * * *" # 毎日0時に実行
  workflow_dispatch: # 手動トリガーも可能

jobs:
  semantic_scholar_search:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests python-dotenv openai

      - name: Run fetch_semantic_scholar.py
        env:
          SEMANTIC_SCHOLAR_API_KEY: ${{ secrets.SEMANTIC_SCHOLAR_API_KEY }}
          DISCORD_WEBHOOK_URL_SCHOLAR: ${{ secrets.DISCORD_WEBHOOK_URL_SCHOLAR }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: python app/fetch_semantic_scholar.py

      - name: Send failure notification to Discord
        if: failure()
        run: |
          curl -H "Content-Type: application/json" \
              -d '{"content": "fetch_semantic_scholar.py ran failed."}' \
              ${{ secrets.DISCORD_WEBHOOK_URL_SCHOLAR }}
